### ISSUE TITLE
Setup backup data rendering user interface

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/2-wheels-1-arm#18]
Depends on #14
- [x] Setup backup data (file) opener
- [x] Setup graph renderer

**Comment by pachakamakk** [comment]
The graph renderer should be front end side, what i understand i should procude for this issue is the production of the log file tracking the algo's progress.

**Comment by Grenadingue** [comment]
_Note: (already discussed in messenger) but said here for clarity_

The job here is not to produce the log file tracking the algo progress, but to read and display it with D3.js. So this part concerns the necessary front-end code with D3.js, and probably some needed back-end code.

**Comment by tomacf** [comment]
I'm scared that for the issues #17 and #18, the work to do and the code will be kind of duplication.

About the render part, we have the same graphic library, the same data format, maybe the same display, the only difference is that one will receive the data one by one from the websocket and the other will receive all the data in one time. (in the end it's the same)

That's why I assigned myself on this issue also.

Maybe for the front it would be more efficient to open an issue for the rendering system (dissociated of how you get the data), an issue for the user interface, and one for the communications (socket.io, file-reader)

**Comment by Grenadingue** [comment]
Yeah I agree, that's why this issue depends on #14 Setup D3.js library

This issue being the final implementation of the generic parts done in #14 plus the specifics needed parts on back/front-end sides for the data backup rendering (e.g. the backup file selector/opener on client/server side)

What you recommend is already kind of what's planned, but maybe that things said in the issue descriptions are not enough comprehensive ? It's easy for me because everything come from my mind, but I understand that I can be not so clear in everyone's mind
